### ISSUE TITLE
{ TypeError: assert.strict is not a function

### ISSUE THREAD

**Issue by OmgImAlexis** [ORESoftware/live-mutex#92]
```ts
lmx broker error: Uncaught Exception event occurred in Broker process: { TypeError: assert.strict is not a function
    at new Broker (/usr/local/bin/proxy/node_modules/live-mutex/dist/broker.js:65:16)
    at Object.<anonymous> (/usr/local/bin/proxy/app/index.js:17:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/bin/proxy/bin/www:4:26)
  [stack]: 'TypeError: assert.strict is not a function\n    at new Broker (/usr/local/bin/proxy/node_modules/live-mutex/dist/broker.js:65:16)\n    at Object.<anonymous> (/usr/local/bin/proxy/app/index.js:17:16)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/usr/local/bin/proxy/bin/www:4:26)',
  [message]: 'assert.strict is not a function' }
```

**Comment by OmgImAlexis** [comment]
This whole commit may need to be fixed. https://github.com/ORESoftware/live-mutex/commit/cb7b296eca50bcd29da0b6e230b29fa736123fb9

I'd highly suggest to add testing to your code before pushing as well as proper commit messages. [This](https://chris.beams.io/posts/git-commit/) is a really good read on that subject.

**Comment by OmgImAlexis** [comment]
Did you mean to use `assert.strictEqual()` instead maybe?

```ts
> import * as assert from 'assert';
{}
> 4
4
> assert
{ fail: [Function: fail],
  AssertionError: [Function: AssertionError],
  ok: 
   { [Function: ok]
     fail: [Function: fail],
     AssertionError: [Function: AssertionError],
     ok: [Circular],
     equal: [Function: equal],
     notEqual: [Function: notEqual],
     deepEqual: [Function: deepEqual],
     deepStrictEqual: [Function: deepStrictEqual],
     notDeepEqual: [Function: notDeepEqual],
     notDeepStrictEqual: [Function: notDeepStrictEqual],
     strictEqual: [Function: strictEqual],
     notStrictEqual: [Function: notStrictEqual],
     throws: [Function: throws],
     doesNotThrow: [Function: doesNotThrow],
     ifError: [Function: ifError] },
  equal: [Function: equal],
  notEqual: [Function: notEqual],
  deepEqual: [Function: deepEqual],
  deepStrictEqual: [Function: deepStrictEqual],
  notDeepEqual: [Function: notDeepEqual],
  notDeepStrictEqual: [Function: notDeepStrictEqual],
  strictEqual: [Function: strictEqual],
  notStrictEqual: [Function: notStrictEqual],
  throws: [Function: throws],
  doesNotThrow: [Function: doesNotThrow],
  ifError: [Function: ifError],
  default: 
   { [Function: ok]
     fail: [Function: fail],
     AssertionError: [Function: AssertionError],
     ok: [Circular],
     equal: [Function: equal],
     notEqual: [Function: notEqual],
     deepEqual: [Function: deepEqual],
     deepStrictEqual: [Function: deepStrictEqual],
     notDeepEqual: [Function: notDeepEqual],
     notDeepStrictEqual: [Function: notDeepStrictEqual],
     strictEqual: [Function: strictEqual],
     notStrictEqual: [Function: notStrictEqual],
     throws: [Function: throws],
     doesNotThrow: [Function: doesNotThrow],
     ifError: [Function: ifError] } }
```

**Comment by ORESoftware** [comment]
yeah it was tested and also compiled with TS tol, hmm, weird, which node.js version are you on?

**Comment by ORESoftware** [comment]
my guess is that you are on an old node version? node 7 does not have assert.strict, but node 8+ should.

**Comment by OmgImAlexis** [comment]
I was on a version of 8. Updated to 12 and still got the error.

**Comment by ORESoftware** [comment]
got it, can you copy the contents of  this file on your machine

```
/usr/local/bin/proxy/node_modules/live-mutex/dist/broker.js:65:16
```

to here?

**Comment by ORESoftware** [comment]
something might be up with your node version, here is the output for for node version 8:

```
> assert
{ [Function: ok]
  fail: [Function: fail],
  AssertionError: [Function: AssertionError],
  ok: [Circular],
  equal: [Function: equal],
  notEqual: [Function: notEqual],
  deepEqual: [Function: deepEqual],
  deepStrictEqual: [Function: deepStrictEqual],
  notDeepEqual: [Function: notDeepEqual],
  notDeepStrictEqual: [Function: notDeepStrictEqual],
  strictEqual: [Function: strictEqual],
  notStrictEqual: [Function: notStrictEqual],
  throws: [Function: throws],
  rejects: [AsyncFunction: rejects],
  doesNotThrow: [Function: doesNotThrow],
  doesNotReject: [AsyncFunction: doesNotReject],
  ifError: [Function: ifError],
  strict: 
   { [Function: strict]
     fail: [Function: fail],
     AssertionError: [Function: AssertionError],
     ok: [Circular],
     equal: [Function: strictEqual],
     notEqual: [Function: notStrictEqual],
     deepEqual: [Function: deepStrictEqual],
     deepStrictEqual: [Function: deepStrictEqual],
     notDeepEqual: [Function: notDeepStrictEqual],
     notDeepStrictEqual: [Function: notDeepStrictEqual],
     strictEqual: [Function: strictEqual],
     notStrictEqual: [Function: notStrictEqual],
     throws: [Function: throws],
     rejects: [AsyncFunction: rejects],
     doesNotThrow: [Function: doesNotThrow],
     doesNotReject: [AsyncFunction: doesNotReject],
     ifError: [Function: ifError],
     strict: [Circular] } }
> 

```

**Comment by ORESoftware** [comment]
@OmgImAlexis  any word on this bird?

**Comment by OmgImAlexis** [comment]
Now try with typescript.

**Comment by ORESoftware** [comment]
how'd it go?

**Comment by ORESoftware** [comment]
any conclusion on this one? will close o/w, pls lmk

**Comment by OmgImAlexis** [comment]
It was an issue. Like I said try with typescript.
